### ISSUE TITLE
Trying to create category root node.

### ISSUE THREAD

**Issue by Hesoy** [aimeos/aimeos-symfony#35] opened 2018-04-16 15:45 UTC
Error No node with ID "0" found, /data/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Tree/Manager/DBNestedSet.php:782

**Comment by aimeos** [comment] 2018-04-16 15:47
Which version do you use?

**Comment by Hesoy** [comment] 2018-04-17 07:28
2018.04.1

**Comment by aimeos** [comment] 2018-04-17 11:28
Thanks for reporting, the issue is fixed now. Please run `composer update`, you will get a new ai-admin-jqadm version (2018.04.6).

**Closed** 2018-04-19 08:00 UTC
